version: 0.2

env:
  variables:
    REPO_NAME: "r-kernel"  # Replace with your ECR repository name
    IMAGE_TAG: "${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}-$(date +%Y%m%d)"  # Simple tag with commit hash and date

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 590183989845.dkr.ecr.ca-central-1.amazonaws.com
      - echo "Using image tag: ${IMAGE_TAG}"

  build:
    commands:
      - echo "Building the Docker image with tag: ${IMAGE_TAG}..."
      - docker build -t $REPO_NAME:${IMAGE_TAG} .

  post_build:
    commands:
      - echo "Tagging the image for ECR..."
      - docker tag $REPO_NAME:${IMAGE_TAG} <account-id>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPO_NAME:${IMAGE_TAG}
      - echo "Pushing the image to ECR..."
      - docker push <account-id>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPO_NAME:${IMAGE_TAG}
      - echo "Docker image pushed successfully."
